# Generated by Django 2.0.3 on 2018-03-24 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msme',
            fields=[
                ('serial_num', models.AutoField(primary_key=True, serialize=False)),
                ('udyog_aadhar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')])),
                ('entrepreneur_name', models.CharField(max_length=50)),
                ('enterprise_name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$')])),
                ('bank_account_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{10,16}$')])),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_ifsc_code', models.CharField(max_length=50)),
                ('partnership_members_amount', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')])),
                ('civil_investment', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{0,11}$')])),
                ('subsidy_provided', models.CharField(max_length=3)),
                ('sector', models.CharField(max_length=14)),
            ],
        ),
    ]
