# Generated by Django 2.0.3 on 2018-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme', '0004_auto_20180325_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msme',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
    ]
