# Generated by Django 2.0.3 on 2018-03-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme', '0005_auto_20180325_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msme',
            name='subsidy_provided',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=8),
        ),
    ]
